all:

clean:
	-rm *~
	$(MAKE) -C scss clean
	$(MAKE) -C tmpl clean
	$(MAKE) -C art clean
	$(MAKE) -C js clean

stage:
	$(MAKE) -C scss stage
	$(MAKE) -C tmpl stage
	$(MAKE) -C art stage
	$(MAKE) -C js stage
